### ISSUE TITLE
企業リスト画面（Home）から詳細画面への値渡しについて

### ISSUE THREAD

**Issue by naokicchi** [webex13-team-12/original-team-app#6]
企業リスト画面（Home）から詳細画面への値渡しして、詳細情報を表示させたい
現状→値渡しができない
もし、値渡しができたとして、値私する内容はfirebaseのオブジェクトID？それとも、オブジェクトそのもの？？
この記事（https://dk521123.hatenablog.com/entry/2021/03/02/001653）
とか見てみたけど、全然理解できなかった、、

**Comment by sei-994** [comment]
載せてくれた記事表示されない、！
多分[これ](https://dk521123.hatenablog.com/entry/2021/03/02/001653)かな？、
【３】$route.params を使用した受け渡しの所とか良いかも。
要はページ遷移の際にキーとなるIDを渡したい感じよね？(IDによって企業詳細ページの内容が変わる感じ)
